pipeline {
    agent {
        docker { image 'vivado:2018.2' }
    }
    stages {
        stage('Checkout') {
            steps { 
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh '/bin/bash -c "cd scripts && source /opt/Xilinx/Vivado/2018.2/settings64.sh && vivado -mode batch -source recreate_prj.tcl" '
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}