pipeline {
    agent {
        docker { image 'vivado:2018.2' }
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd scripts && source /opt/Xilinx/Vivado/2018.2/settings64.sh && vivado -mode batch -source create_project_tcl.tcl'
            }
        }
    }
}
