pipeline {
    agent {
        docker { 
            image 'vivado:2018.3'            
        }
    }
    stages {
        stage('Checkout') {
            steps { 
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh '/bin/bash -l scripts/build_fpga.sh'
            }
        }
    }
    post { 
        always {             
            archiveArtifacts artifacts: 'vivado/**/impl_1/*.bit'
            plot csvFileName: 'plot-e14c354f-d4b8-4942-9e76-a2423ad3a291.csv', csvSeries: [[displayTableFlag: true, exclusionValues: 'LUT(%),FD(%),LUT Combining(%),DSP48(%),RAMB/FIFO(%)', file: 'utilisation.csv', inclusionFlag: 'OFF', url: '']], group: 'utilisation', style: 'line', title: 'Resources utilisation', useDescr: true, yaxis: '[%]'
            cleanWs()
        }
    }
}
